### ISSUE TITLE
throw user-select: none on everything

### ISSUE THREAD

**Issue by kylemcdonald** [ofZach/pgElectron#15]
the less it feels like a web app, the better.

unless there is an error message we specifically want people to be able to copy and paste to find out more (or it could link to a forum topic directly).

edit: it would also be cool if it didn't move around when scrolling -- but this is an important feature to have when the addons list is long enough, so it's not a priority.

**Comment by ofZach** [comment]
right will do. the console should probably be selectable since if people have issues, they can paste up the output of the command line tool...
