### ISSUE TITLE
default project name should be something unique on launch

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#18]
so that it doesn't default to update, ie, if it's always "myApp" the app will launch with update functionality once that project exists.  Maybe we can look at what processing or arduino does for reference or leave the name field blank (with a suggestion not an actual value)

**Comment by Daandelange** [comment]
Blank would be better IMO and we can use a placeholder saying "myGeniusApp" or something similar

**Comment by ofZach** [comment]
I'm trying to keep this PG similar to the simple one, so I don't think blank makes sense.  I've added something that increments a counter, so we do mySketch, mySketch1, mySketch2, etc...   I prefer it to be as simple as possible to make a new sketch.

**Comment by Daandelange** [comment]
ok :)
Instead of incrementing, it would be funny (later on) to call them "myGeniusSketch", "mySuperSketch", "myBrandNewSketch", "myAmazingSketch", etc.

**Comment by ofZach** [comment]
https://github.com/weaver/moniker is interesting if we wanted to try that ... :) 

also the way I am doing this is kind of ghetto, I am calculating this in index.js: 

https://github.com/ofZach/pgElectron/blob/master/index.js#L72-L73

but since I don't want to save it out (and alot of stuff saves out the settings) I delete it here: 

https://github.com/ofZach/pgElectron/blob/master/app.js#L272-L277

maybe it should be it's own callback?  (just flagging that this is kind of in-elegant)

**Comment by Daandelange** [comment]
Yes, a lot of stuff trigger a `settings.json` write-out which is kind of dirty but it simplifies the rest of the code a lot and prevents having duplicate code.

But... I don't think you have to put this in `defaultSettings` (also called `obj`).
I'll try to move this apart and integrate moniker :)

**Comment by Daandelange** [comment]
@ofZach I'll let you close this issue if approved :+1:

**Comment by Daandelange** [comment]
Todo: install moniker with npm or exclude `npm_modules` from `.gitignore` (or add it somehow as a dependency)
