### ISSUE TITLE
platforms should be toggle (not multiselect) with default toggled on

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#2]
and we should not let there be no platform selected :)

**Comment by Daandelange** [comment]
How to detect the default platform ? Can we read this from the OF_path ?

**Comment by ofZach** [comment]
this should be in settings.json -- it seems like as we do releases, like ios / osx we 'd need to change this file.

**Comment by Daandelange** [comment]
ok, thanks :)
But what about the github master version? `settings.json` doesn't come with the repo and is auto-generated by `index.js`. This could be problematic.

**Comment by ofZach** [comment]
settings.json should not be auto generated and should come with the repo, that's how it was before

**Comment by Daandelange** [comment]
Ok, but if the file exists it won't auto-generate.
Anyways, same problem: how to set the default target from the github repo ?
Maybe auto-generate isn't that bad and we could set the default target from an OS detection ?

**Comment by ofZach** [comment]
no I don't think we can, I think this has to be set by hand as we do releases.  this is similar to the xml file that comes the PG now.   I don't think it can all be automated yet.

**Comment by Daandelange** [comment]
I think you partially fixed this in your commits from today, didn't you ?
I can select multiple and not deselect one.

I can make something to select default on startup

**Comment by ofZach** [comment]
I guess I meant we should do this kind of approach instead of a multi-select form...  

<img width="314" alt="screen shot 2015-08-21 at 1 07 38 pm" src="https://cloud.githubusercontent.com/assets/142897/9414341/a58c91da-4805-11e5-90c1-2c980f1b050b.png">

**Comment by Daandelange** [comment]
Added a getSelectedPlatforms() function which reads the toggle states.

**Comment by ofZach** [comment]
Sweet thanks!  What I also wasn't sure about it how to hide options (or grey them out) in advanced mode (in advance mode you should only see the default platform highlighted and no toggle-able)

**Comment by Daandelange** [comment]
This can be simply done by CSS but first I'd like to make sure there's always 1 platform selected.
For the moment none is selected on launch which would be a problem in non-advanced mode.

**Comment by ofZach** [comment]
I think we could set that here: 

```
for (i = 0; i < platforms.length; i++) {
    if (platforms[i] === defaultPlatform){
            ;  // set some other identifier
            } else {
    $(".platformSelect").append("<div class='platform'>" + platforms[i] + "</span>");
            }
}
```

**Comment by Daandelange** [comment]
Not needed, CSS will handle it.
The thing is that the git repo has no `defaultPlatform`...

**Comment by ofZach** [comment]
yeah we should just use osx in the settings.json and then change it later for releases...
