### ISSUE TITLE
use clearer / less nerdy names for platforms?

### ISSUE THREAD

**Issue by kylemcdonald** [ofZach/pgElectron#21]
right now: `osx, win_cb, vs, ios, linux, linux64, linuxarmv6l, linuxarmv7l`

perhaps: `OS X (Xcode), iOS (Xcode), Windows (Visual Studio 2015), Linux 32-bit (Code::Blocks), Linux 64-bit (Code::Blocks), Linux ARMv6 (Makefiles), Linux ARMv7 (Makefiles)`

instead of `OS (Build system)` we could also do `Build system (OS)`

**Comment by Daandelange** [comment]
Done but it takes up a lot of UI space... could we make the platform toggles a little smaller ?

**Comment by Daandelange** [comment]
Regardless of the graphics, this issue can be closed IMO.
