### ISSUE TITLE
open link to ofxaddons instead of showing tooltip

### ISSUE THREAD

**Issue by kylemcdonald** [ofZach/pgElectron#22]
instead of showing a tooltip on the "Addons" label, maybe we should use an icon (like the glyphicon/halflings "share" icon) and this technique https://github.com/jlord/git-it-electron/pull/35 to open a window to ofxaddons.com in a browser.

**Comment by Daandelange** [comment]
Good idea, looks nice :)
The technique was already used but got broken somehow...
