### ISSUE TITLE
maybe we only need console when you do something like generate a project, etc

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#24]
right now the always on screen (if button checked) console seems kind of excessive to me, it feels like we get a lot of value by popping the log up on the overlay on create or update.  Maybe we don't need the additional bottom console?

**Comment by Daandelange** [comment]
I like the bottom console which allows you to trace back what happened on generating/updating projects; even after closing the success modal.
27ed863 hides the bottom console on the settings page. It can easily be hidden on the batch page too in this line: https://github.com/ofZach/pgElectron/commit/27ed863d01eca8a6b74f9c40a02c10cee46b6ff2#diff-ed5f959bb9eee3684a44c6e6ed7d1cf1R216

**Comment by ofZach** [comment]
what if the console was an options only thing?  I really don't think end users will need this and or understand it (vs the console output from the action).  I think we should keep the UI as simple as possible here.   @kylemcdonald what do you think?  Personally, I feel like it's redundant.

**Comment by ofZach** [comment]
(also, I've made show console tools a settings thing, you can enable it via settings.json but it's not an "option" for end users...)

**Comment by Daandelange** [comment]
Ok, now it makes more sense to me.

This is how I see it now:
- An end-user option to "Show console messages" shows console feedback after each operation. (toggle btn if success, always shown if error) _[it vanishes on closing the modal]_
- Another hidden option shows the console at the bottom of the page which keeps track of all console history.

And as I said in https://github.com/ofZach/pgElectron/issues/20#issuecomment-134210362, IMO it's still weird not to show the console messages if an error occurred. So maybe if the "Show console messages" setting is off, we can show a toggle button when an error occured. (?)

**Comment by ofZach** [comment]
how about a show console messages button on the success / failure overlay and not in options?   we could show console in failure, but in success make it an option?  (that way, we keep it out of settings). 

I like the hidden option, so if you (or anyone) wants to monitor everything they can, but I don't think this is a normal need people will have.

**Comment by Daandelange** [comment]
Sounds good too.
So:
- No UI setting for "Show console" but always show it on success[_toggle_] / failure modals
- A hidden `settings.json` setting lets you enable the console at the bottom of the generate pages.
- (maybe) a PG readme states that more settings are available in settings.json

**Comment by kylemcdonald** [comment]
I'm for removing it completely, and only showing feedback on errors. The
use case for it is "something went wrong and I want to copy this message
and ask on the forum", which the dialog allows.

I don't see a use case for showing the console in any other case, except
during development of the PG itself, which is not an end-user facing
application.

**Comment by Daandelange** [comment]
Ok, this last commit changes it like that.
- Console feedback is only shown on errors.
- There's a hidden console setting allowing to see all console feedback.

Is this how we want it ?
