### ISSUE TITLE
moniker can be discouraging

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#29]
as much as love the dynamic name generation, this feels a bit too much: 

<img width="430" alt="screen shot 2015-08-26 at 10 17 08 pm" src="https://cloud.githubusercontent.com/assets/142897/9511052/4b9e764a-4c40-11e5-893a-4f912766a64e.png">

**Comment by ofZach** [comment]
maybe there needs to be a recycle button if you are using an autogenerated name to cycle away from negativity: 

<img width="326" alt="screen shot 2015-08-26 at 10 21 22 pm" src="https://cloud.githubusercontent.com/assets/142897/9511102/debf9a1c-4c40-11e5-8377-5fb56601567c.png">
<img width="320" alt="screen shot 2015-08-26 at 10 21 07 pm" src="https://cloud.githubusercontent.com/assets/142897/9511100/deba247e-4c40-11e5-8128-bfb996dd61b5.png">
<img width="342" alt="screen shot 2015-08-26 at 10 20 59 pm" src="https://cloud.githubusercontent.com/assets/142897/9511101/debd9e74-4c40-11e5-9cba-404e11794e52.png">

I'm also ok with mySketch1, mySketch2, for now...

**Comment by Daandelange** [comment]
Another option is to make / grab a dictionary of friendly & nice adjecectives.

**Comment by Daandelange** [comment]
I also like the sense of humor of automatically generated sketch names but I agree you picked a few mad ones.
I quickly composed this `sketchAdjectives.txt` dictionary so it should be way better now!

**Comment by Daandelange** [comment]
But adding a small "generate project name" gui element could be nice anyways :)

**Comment by Daandelange** [comment]
@ofZach can we consider this as fixed ?

**Comment by ofZach** [comment]
yes it feels a little better with the dictionary....  curious what @kylemcdonald thinks but closing for now.

**Comment by Daandelange** [comment]
(I also added the "Recycle"/regenerate glyph icon in 2140b92 )

**Comment by kylemcdonald** [comment]
i looked through the new dictionary and i think it's more appropriate now. i consider this closed too.

but regarding the aesthetic of the names, i would take a different route. stop reading here unless you want to entertain the possibility of going a different route :)

myAdjectiveSketch is fun, but i see two issues:
1. it will necessarily repeat after ~200 calls
2. an adjective alone doesn't create an image for me

i did a mockup of adjectiveNoun using the 500 most common nouns and adjectives: https://gist.github.com/kylemcdonald/f6b53782f06fa3a19749

```
religiousEvidence
tallEffect
paleOil
tremendousSister
assistantSenate
sharpBenefit
competitiveMission
jointFall
toughAttention
dryPlan
largeStage
westernCondition
necessaryCrime
sufficientStation
activeConsumer
socialWeapon
commercialExecutive
extraMember
gladIdea
loudMeeting
```

another approach could be to go for the aphex twin look, and use a small markov chain. even for length 1 they're pretty fun:

```
char=$1
for i in `seq 8`; do
    printf $char
    char=`egrep -o $char. list-adjectives.txt | gshuf -n 1 | cut -c 2`
done
echo $char
```

```
$ echo 'abcdefghijkmnopqrstuvwxyz' | fold -w1 | xargs -L 1 ./markov.sh
arimimufi
bontociad
cablysoma
deryerall
enalignef
feredatel
glisyctiv
huameladl
iacanindo
jusorelea
knghowial
mprmiexto
nderetiap
ompompore
printrice
qutingonn
riealleti
stideflui
tesistorn
uccoarvak
vexigrfun
wnalenver
xticrruar
ypreftiem
zitinyonf
```

**Comment by ofZach** [comment]
this thread is getting interesting :) 

I think one of the main issues is that none of these approaches produce files that are easily sortable the same way (generally) saying sketch3, sketch4, or processings: 

sketch_datea, sketch_dateb, sketch_datec...

is sortable.  I've found that I actually forget the name sometimes, and after I create it I have folders that look like this: 

<img width="176" alt="screen shot 2015-09-03 at 2 15 25 am" src="https://cloud.githubusercontent.com/assets/142897/9651678/b47d3542-51e1-11e5-9b1d-ee7dd1351464.png">

and it's usually somewhere in the middle, vs right at the end / easily identifiable by having the date in the name. 

I guess I generally prefer a more utilitarian approach here :)  I feel like we are trying to be too cute, and it might be better to aim for most functional ?

**Comment by Daandelange** [comment]
Interesting discussions :)

But I'm wondering how many people will actually use this name-generation functionality.
I mean, is it worth paying so much attention to this little PG detail / feature ?

In my case, I'd only use it to quickly try something out, a quick OF sketch which will probably get deleted once it works (after copy/pasting it into my real project which has a "real" name).
Why would you use a randomly generated name if you have an important OF project/app in mind ?

So for me, the most important thing is that it makes me laugh on generating the sketch... so I'd go for cuteness rather then functionality.

@ofZach If you want to find back a sketch by date, `Finder.app` (or equivalent) can always sort files by modification/creation date rather then by name...

**Comment by ofZach** [comment]
from experience beginners often times don't name their sketches well or at all -- personally, I'd vote for the most functional vs the cuteness of autogenerated names.  But that's more from using it now for a bit (the auto generated names are definitely fun) and finding it kind of messy / not very helpful at some point.  I promise that beginners will have folders that look like my screenshot above, I think we are doing a disservice to them with this approach vs. something more practical. 

my suggestion is for RC2, add a flag to settings (where you can have the current moniker approach or the p5 appraoch) and then we can ask people to a/b test a little and get feedback from the community.

**Comment by kylemcdonald** [comment]
zach, i totally agree. i think we're basically at the point where getting feedback/testing is the next step in general.
