### ISSUE TITLE
platform selection should be disabled / grey'd out if advanced toggle not set

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#3]
picking platforms is an advanced option.  We should use the highlighted default platform (platform should be set in the settings.json)

**Comment by Daandelange** [comment]
The platform selection, do you need to have 1 for (advanced) single update **AND** 1 for batch updating ? Or is having 1 targets selection in `settings` enough for both ? (I guess so)

**Comment by ofZach** [comment]
hmmm.... 

I think in non-advanced, it should say "osx" with the other platforms grey'd out on both the generate page and the update multiple page.  In advanced it should be selectable in both generate and update multiple.    ( I also think it shouldn't be a multi-select, but more like the PG roadmap which has this illustrated kind of well). 

I think it's a more active config then "OF location", and something that I imagine people may change more often if they are in advanced mode based on what they are doing....

**Comment by ofZach** [comment]
(sorry for the OSX centrisim.... it should say whatever platform is the default)

**Comment by Daandelange** [comment]
Ok, but then I'd opt for just "Selected platform: whatever" in simple mode;
and advanced showing the platform choice in both single & batch screens.

**Comment by ofZach** [comment]
sounds good -- the current PG simple is a good reference for that.
