### ISSUE TITLE
Using path in index.js causes error

### ISSUE THREAD

**Issue by Daandelange** [ofZach/pgElectron#33]
Using path in index.js (server side) causes an error.., sometimes yes, sometimes not.

In this case it happens when re-generating a `moniker` name (which uses `path`)

```
Uncaught Exception:
TypeError: Cannot read property 'join' of undefined
    at EventEmitter.<anonymous> (/Developer/openFrameworks/projectGenerator-darwin-x64/projectGenerator.app/Contents/Resources/app/index.js:374:25)
```

I tried caching it like `tmpPath = require('path');` but same issue, it sometimes crashes with the same error.
Btw, it happens mostly when the Gui switched to (single) update mode but I can't figure out what's causing the problem.

**Comment by ofZach** [comment]
I have def seen this before and solved it before using what I do in getDirectories()....  make temporary path and fs variables inside the function and use those....  I'd look for any path.join (or use of path / fs inside the functions), and replace it with this pattern maybe?

**Comment by Daandelange** [comment]
Oh, you mean you can't call `path` from ipc.on('something', function(){ /\* path stuff here... /*});` ?
I'll try something :)

**Comment by Daandelange** [comment]
Oh, I forgot to replace the 2nd path var with the tmpPath var, that's why it didn't work ^_^
