### ISSUE TITLE
win32 error

### ISSUE THREAD

**Issue by liquidzym** [ofZach/pgElectron#34]
sorry to post here if this is not ready yet,i'm just curious to see the new pg.so i did packed as win32 app,somehow it didn't work,am i missing something?
cheers
![win32 error](https://cloud.githubusercontent.com/assets/51957/9704755/11d41b52-54e4-11e5-9f0e-a51f15309bd2.jpg)

**Comment by ofZach** [comment]
I guess you are missing a node module.

I'll take a look at windows today and try to post a windows Zip up, for sure there's some OS X / Linux specific stuff right now esp about flags to re command line tool and the path to the command line app.

**Comment by Daandelange** [comment]
Did you run `npm install` from the pgElectron directory ? That should download moniker.
(and also, master is way behind, try using the `demantic-ui` branch)

**Comment by ofZach** [comment]
About windows, just adding a quick note that the command line tool expects "/" not "-" for params, and likely the path to the executable is different on each platform.    I did test this at one point and it worked but we need to do some smart stuff in index.js....

**Comment by liquidzym** [comment]
ok,i did missed that npm install,i'm using the demantic-ui branch,but after running the npm install command,still got other issue.
![issue](https://cloud.githubusercontent.com/assets/51957/9708375/35fe08bc-554d-11e5-891e-b8b4b2a3d819.jpg)

**Comment by Daandelange** [comment]
Thanks for the additional info. Weird that the variable name stays as is in the path; it might be a variable parsing problem (`__dirname`).
On OS X the error looks like this when the dictionary is not found.
![Same error on OSX](https://cloud.githubusercontent.com/assets/1329784/9711747/4688041e-5546-11e5-9c00-a0a665d44821.png)

If you wanna work around it, you can look at `index.js` in `function getStartingProjectName()`

**Comment by liquidzym** [comment]
ok,i just download the new packed version,it's working,so i'm closing it.
