### ISSUE TITLE
addons list include non addon folders (like obj from makefile system).

### ISSUE THREAD

**Issue by bakercp** [ofZach/pgElectron#36]
![openframeworks_project_generator](https://cloud.githubusercontent.com/assets/300484/9753366/4fc51b0c-5681-11e5-82cb-5005772caf1e.png)

**Comment by bakercp** [comment]
Maybe solution just to list things that start with `ofx`?

**Comment by Daandelange** [comment]
Note: Arturo already made the change in #38 :)

**Comment by bakercp** [comment]
Great thanks closed with e62ed82
