### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by genekogan** [ofZach/pgElectron#37]
does this work on 0.8.4?  i get this when i start up, and then the platform selector is unavailable. guessing it's missing some file that's in 0.9 RC 
<img width="506" alt="screen shot 2015-09-09 at 12 53 32 am" src="https://cloud.githubusercontent.com/assets/1335251/9753631/8d9cb122-568d-11e5-8e7b-c150ef6538d1.png">

**Comment by ofZach** [comment]
no it only works on 0.9 (master) because of the templates and where they are located now....

**Comment by ofZach** [comment]
but it's good to see this error (I think I have fixed this error in the javascript already but I need to update the OSX apps).

**Comment by ofZach** [comment]
for mental sanity, just reminding myself that fix is already done here: 
https://github.com/ofZach/pgElectron/blob/master/index.js#L280-L289
