### ISSUE TITLE
advanced mode toggle

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#5]
we need an advanced mode in settings for allowing for platform selection and for doing the batch updating (which we should not let beginners do...)

**Comment by Daandelange** [comment]
Note: in advanced mode, the body gets a `advanced` class so most of the functions can just be shown/hidden with css properties. :)
You can also add an `advanced-feature` class to HTML elements that are only for advanced use.

**Comment by ofZach** [comment]
cool checking it out now!

**Comment by ofZach** [comment]
oh we got wide -- I'm not sure about this change :)

**Comment by Daandelange** [comment]
oups! I forgot to revert that personal change, i'll revert it in my next commit :)
(it's to have the developper tools aside)
