### ISSUE TITLE
settings i/o

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#6]
settings should have a save option so that on relaunching they are remembered

**Comment by Daandelange** [comment]
Already handled for OF_path ( see https://github.com/ofZach/pgElectron/commit/e085bbd9b0022853aa52712dc7af04599fc311d4 )
I'll make it for targets too, and maybe remember the last used projectPath ?

**Comment by Daandelange** [comment]
Should the PG remember the targets from last launch or use the default target ?

**Comment by ofZach** [comment]
I think it should remember the OF path and the advanced setting (ie, anything in options), but I don't think remembering the other stuff is necessary (yet!)...

**Comment by Daandelange** [comment]
Then we can close this issue. :)
