### ISSUE TITLE
we should capture the output of the command line tool and allow people to see it somehow

### ISSUE THREAD

**Issue by ofZach** [ofZach/pgElectron#7]
ala,
http://stackoverflow.com/questions/12941083/get-the-output-of-a-shell-command-in-node-js

**Comment by Daandelange** [comment]
Just added a console in 236b52c20c9cd6972fc44ce10e593f14cb471874 :)
Once we have a success feedback message, we should still add a button in it to reveal the console output from only the last executed command.

**Comment by Daandelange** [comment]
Here's what I get from successfully generating a new project:

```
Stdout:
[notice ] setting OF path to: /Developer/openFrameworks
[notice ] setting up a new project
[notice ] target platform is: osx
[notice ] project path is: /Developer/openFrameworks/apps/untitled folder/myAppadg
[warning] ofDirectory: createDirectory(): directory already exists: "/Developer/openFrameworks/apps/untitled folder/myAppadg/myAppadg.xcodeproj/project.xcworkspace/"
[warning] ofDirectory: createDirectory(): directory already exists: "/Developer/openFrameworks/apps/untitled folder/myAppadg/myAppadg.xcodeproj/xcshareddata/xcschemes/"

Error:
null

Stderr:
[ error ] ofFile: remove(): file does not exist
[ error ] ofFile: remove(): file does not exist
[ error ] ofFile: remove(): file does not exist
[ error ] ofFile: copyTo(): source file does not exist
[ error ] ofFile: remove(): file does not exist
```

I guess `stderr` is not important but `stdout` could be useful ?
Is it a good idea to put `stdout` in the button-retrieval in the success message ?

**Comment by Daandelange** [comment]
Also, the "Show console output" button is only shown in advanced mode, it that OK ?
(on success, always shown on failure)

**Comment by Daandelange** [comment]
( graphics are still very basic and may need to be reviewed )

**Comment by ofZach** [comment]
I think your project generator is out of date, the output should be alot cleaner now.   can you try to update the projectGenerator submodule and recompile it?  My output looks like:

```
[notice ] PG_OF_PATH variable is set to: /Users/zachlieberman/Documents/openframeworks/git/openFrameworks
[notice ] using env var for OF path
[notice ] /Users/zachlieberman/Documents/openframeworks/git/openFrameworks/apps/projectGenerator/commandLine/bin/temt does not exist, using 'create' mode
[notice ] setting OF path to: /Users/zachlieberman/Documents/openframeworks/git/openFrameworks


[notice ] -----------------------------------------------
[notice ] setting up a new project
[notice ] target platform is: osx
[notice ] project path is: /Users/zachlieberman/Documents/openframeworks/git/openFrameworks/apps/projectGenerator/commandLine/bin/temt
[notice ] saving addons.make
[notice ] project created!
[notice ] -----------------------------------------------


1 project created in 0.015625 seconds
```

**Comment by Daandelange** [comment]
I'll give it a look but this changes should work for both ^_^

**Comment by ofZach** [comment]
cool I love the overlay after creating ! -- the console at the bottom might be better as an option you can turn on and off?  I think it's more for debugging then anything else but the command line output of the generate or update commands seems really valuable.

**Comment by Daandelange** [comment]
It's already an option, except when there's an error.
The console in the bottom has it's own option and the console button within the success message is only shown when advanced mode is activated.

**Comment by ofZach** [comment]
(sorry I think I meant say I think console should be toggled independent of advanced mode... it seems a little odd to have settings appear / disappear based on advanced.  another option is grey'd out in non advanced --- in general grey'd out is nicer IMO then hidden, it feels like the UI gets complex when we hid things from people)

**Comment by Daandelange** [comment]
Ok I'll make it only dependant on the console setting.
You mean greying out the button, not the console right ?

**Comment by ofZach** [comment]
yes -- greying out the button might be good (from a UI perspective) or just separating it from advanced mode....  thanks!
